FROM golang:1.24.5-alpine AS builder

RUN apk add --no-cache git gettext ca-certificates

RUN go install github.com/cespare/reflex@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN mkdir -p tmp

EXPOSE 8080

CMD sh -c "envsubst < ./config/config.template.yaml > ./config/config.development.yaml && reflex -v -c config/reflex.conf"
